# Generated by Django 4.2 on 2025-11-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacultyDetails",
            fields=[
                ("facultyid", models.IntegerField(primary_key=True, serialize=False)),
                ("facultyname", models.CharField(max_length=100)),
                ("facultyage", models.IntegerField()),
                ("facultyresearch", models.TextField()),
            ],
        ),
    ]
