# Generated by Django 4.2 on 2025-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Awardtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Facultynomincations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facultyid", models.IntegerField()),
                ("facultyname", models.CharField(max_length=100)),
                ("award", models.CharField(max_length=100)),
            ],
        ),
    ]
