# Generated by Django 4.2 on 2025-11-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0002_awardtype_facultynomincations"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Facultynomincations",
            new_name="Facultynominations",
        ),
    ]
