# Generated by Django 4.2 on 2025-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0003_rename_facultynomincations_facultynominations"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookDetails",
            fields=[
                ("bookid", models.IntegerField(primary_key=True, serialize=False)),
                ("bookname", models.CharField(max_length=100)),
                ("authorname", models.CharField(max_length=100)),
                ("currentlycheckedout", models.BooleanField()),
                ("numberoftimescheckedout", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BookReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentid", models.IntegerField()),
                ("bookname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                ("studentid", models.IntegerField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("major", models.TextField()),
                ("year", models.IntegerField()),
                ("gpa", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Awardtype",
        ),
        migrations.DeleteModel(
            name="FacultyDetails",
        ),
        migrations.DeleteModel(
            name="Facultynominations",
        ),
    ]
