# Generated by Django 4.2 on 2025-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0004_bookdetails_bookreservation_studentdetails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="year",
            field=models.TextField(),
        ),
    ]
