# Generated by Django 4.2 on 2025-12-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0005_alter_studentdetails_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreservation",
            name="bookid",
            field=models.IntegerField(default=0),
        ),
    ]
