# Generated by Django 4.2 on 2025-12-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0006_bookreservation_bookid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreservation",
            name="firstname",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="bookreservation",
            name="lastname",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
