# Generated by Django 4.2 on 2025-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0007_bookreservation_firstname_bookreservation_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreservation",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bookreservation",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
    ]
