# Generated by Django 4.2 on 2025-12-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0008_alter_bookreservation_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="authorname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bookdetails",
            name="bookname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bookreservation",
            name="bookname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bookreservation",
            name="firstname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bookreservation",
            name="lastname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="firstname",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="lastname",
            field=models.TextField(max_length=100),
        ),
    ]
