# Generated by Django 4.2 on 2025-12-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0009_alter_bookdetails_authorname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="currentlycheckedout",
            field=models.TextField(),
        ),
    ]
