# Generated by Django 4.2 on 2025-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0010_alter_bookdetails_currentlycheckedout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="currentlycheckedout",
            field=models.CharField(default="No", max_length=3),
        ),
    ]
