# Generated by Django 4.2 on 2025-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0011_alter_bookdetails_currentlycheckedout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="currentlycheckedout",
            field=models.BooleanField(default=False),
        ),
    ]
