# Generated by Django 4.2 on 2025-12-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0012_alter_bookdetails_currentlycheckedout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreservation",
            name="bookid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faculty.bookdetails"
            ),
        ),
        migrations.AlterField(
            model_name="bookreservation",
            name="studentid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faculty.studentdetails"
            ),
        ),
    ]
